- name: Task helper script
  ansible.builtin.shell: 
    cmd: curl -1sLf 'https://dl.cloudsmith.io/public/task/task/setup.deb.sh' | sudo -E bash
  become: true
  when: patching == 'debian'

- name: Install packages
  ansible.builtin.package:
    name: "{{ pkg }}"
    state: "{{ headless_role_state }}"
    update_cache: yes
  become: true
  with_items: "{{ packages[headless_role_mode][patching] }}"
  loop_control:
    loop_var: pkg

# TODO: run lazydocker install helper script
