headless_role_state: latest

packages:
  alpine:
  - busybox-extras
  - cmatrix
  - curl
  - git
  - github-cli
  - go
  - go-task
  - nano
  - powershell
  - tailscale
  - tmux
  - wget
  debian:
  - acpi
  - bc
  - btop
  - c3270
  - cmatrix
  - curl
  - fbterm
  - fortune
  - gh
  - git
  - golang
  - golang-golang-x-tools
  - lazygit
  - mc
  - ncal
  - ncdu
  - network-manager
  - postgresql-client
  - smbclient
  - tmux
  - unzip
  - vlock
  - w3m
  - wget
