- name: Install Curl
  ansible.builtin.package:
    name: curl
    state: present
  become: true

- name: Helper Script
  ansible.builtin.shell: 
    cmd: curl -fsSL https://tailscale.com/install.sh | sh
    creates: /usr/bin/tailscale
  become: true